### ISSUE TITLE
Facing flickery effect when menu is opening up

### ISSUE THREAD

**Issue by Lokesh235** [jaysoo/react-native-menu#24]
Have tried the simple example. It seems like menu is rendering many times which is causing flickering effect when I open the top right drawer icon.

**Comment by naiyt** [comment]
I seem to have run into this with multiple RN libraries...it seems like there's a bunch of weird issues with RN and Android animations currently.

I made a fork that lets you optionally disable the menu opening animation: https://github.com/naiyt/react-native-menu/commit/156b349c4334ca940c270498408c7b08728d456d

It kind of sucks, but I'm using it as a compromise for now (until issues with RN Android animations get fixed, or I learn more about what's breaking them in a lot of cases).

Use it like:

``` javascript
<MenuContext animate={false}
 ...
</MenuContext>
```

Install with: `npm i https://github.com/naiyt/react-native-menu --save`

I'm not going to open a PR because I think a better solution needs to be found. But posting this here in case it's useful for anyone.

**Comment by sodik82** [comment]
I believe it is related to https://github.com/facebook/react-native/issues/6278 . Can be fixed (workerround) when you properly play with initial value.

**Comment by nico1510** [comment]
I noticed this too and I think that not using an animation (or at least being able to disable it) is a better option than this flickering. Maybe you should send a pull request anyway @naiyt ?

**Comment by sodik82** [comment]
@nico1510  better solution is https://github.com/instea/react-native-popup-menu/commit/ce85522cd82466fda71eae3ad530eac4ce361082 (or use it directly as an alternative)

**Comment by idan-ratzabi** [comment]
still happening
