### ISSUE TITLE
MenuTrigger sometimes does not work

### ISSUE THREAD

**Issue by kelvinaliyanto** [jaysoo/react-native-menu#7]
Is this version stable? because I tried to click the MenuTrigger in dropdown and sometimes it shows MenuOptions and sometimes it does not show. It is just way too random. Sometimes even a reload (without changes on the code) can make the MenuTrigger not showing the MenuOptions. How to debug?

**Comment by UKDeveloper99** [comment]
My trigger isn't working at all I copied the dropdown menu directly from the example. It's just not opening anything.

**Comment by UKDeveloper99** [comment]
Also I don't understand why there is open/toggle functions when the trigger is automatic right? Unless the example is missing the usage of the functions, which would explain why my dropdown menu isn't opening.

**Comment by UKDeveloper99** [comment]
So after a bit of trial and error with the menu code I can get the menu to open if I don't supply any styles to the menu e.g.
`<Menu style={styles.dropdown.. // get rid of style`

But then I've got a menu that doesn't look like a dropdown menu because it's got no styles.

The whole trigger system seems extremely clunky, the slightest change can break the whole thing. I was trying to reproduce the dropdown menu like in the animated examples on the phones on the README page, with 3 options.

Because in the examples source code you have some text that renders above the options prompting the user to choose one
`renderOptionsContainer={(options)` => <ScrollView><Text>CHOOSE SOMETHING....</Text>{options}</ScrollView>}>`

but if you try to remove the text component here it breaks again. And the dropdown menu doesn't open anymore. 

It seems the only thing that defines if it's a dropdown menu or not is this renderOptionsContainer parameter.

Some examples of of how to achieve a dropdown menu like in the animated examples would be good
@jaysoo any ideas?

**Comment by UKDeveloper99** [comment]
Seems everything breaking is related to the styles, if I even do something as simple as alignItems='center' on the container view that contains the menu it breaks and the menu won't open. Maybe this is ES6 related, I noticed you used React.createClass rather than extend component.

**Comment by UKDeveloper99** [comment]
I really like the functionality of this lib but unfortunately it's too unstable to use in a live project. I'll check back to see if there's been any fixes though.

**Comment by kelvinaliyanto** [comment]
@UKDeveloper99 Hi, I also still struggle with this problem. The thing is that it sometimes works and sometimes does not. The way you place your MenuContext is also I believe as one of the source of the problem. Although this is the best dropdown plug-in that I can find, but if this is THIS unstable, I think I will not have any other options than to use other less powerful but more stable alternative. I hope this issue will be fixed in the near future. Cheers!

**Comment by jaysoo** [comment]
@kelvinaliyanto @UKDeveloper99 Sorry for the delay in response. I'll take a look this week on the cause of the issue. Do you have a small example I can run BTW?

**Comment by xumine** [comment]
This issue seems related with some issue of UIManage.measure.
My menu is hidden randomly when UIManager.measure returns:
    UIManager.measure Object {x: 0, y: 0, w: 414, h: 656, px: 413.3333333333333, …}
And the menu is shown when the result is:
    UIManager.measure Object {x: 0, y: 0, w: 414, h: 656, px: 0, …}

So I solved my issue with a workaround to set the px to 0, in makeMenuContext.js

```
onLayout() {
  const handle = React.findNodeHandle(this.refs.Container);
  UIManager.measure(handle, (x, y, w, h, px, py) => {
    this._ownMeasurements = {x, y, w, h, px:0, py};
  });
},
```

**Comment by HaraKeisuke** [comment]
@xumine  Thanks!!

**Comment by Lokesh235** [comment]
I am also facing the problem with MenuTrigger ...I copied code from example but the menu is not showing up. Is there any fix for this yet?
